version: 2.1

orbs:
  architect: giantswarm/architect@4.35.5

workflows:
  build:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-to-giantswarm-playground-catalog
          context: architect
          executor: app-build-suite
          chart: gatling
          app_catalog: giantswarm-playground-catalog
          app_catalog_test: giantswarm-playground-test-catalog
          requires:
            - push-to-registries
          filters:
            tags:
              only: /^v.*/
