version: 2.1
orbs:
  architect: giantswarm/architect@4.17.0

workflows:
  build:
    jobs:
      # Ensure that for every commit (all branches), and for every new release tag,
      # an image is pushed to Quay.
      - architect/push-to-docker:
          name: push-to-quay
          image: "quay.io/giantswarm/gatling-app"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          filters:
            tags:
              only: /^v.*/

      # build the helm chart and push to the playground catalog.
      - architect/push-to-app-catalog:
          name: "package and push gatling-app chart"
          app_catalog: "giantswarm-playground-catalog"
          app_catalog_test: "giantswarm-playground-test-catalog"
          chart: "gatling-app"
          persist_chart_archive: true
          executor: "app-build-suite"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/run-tests-with-ats:
          name: execute chart tests
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - "package and push gatling-app chart"
