version: 2.1

orbs:
  architect: giantswarm/architect@4.30.1

workflows:
  build:
    jobs:
      - architect/push-to-docker:
          context: architect
          name: push-to-quay
          image: quay.io/giantswarm/gatling-app
          username_envar: QUAY_USERNAME
          password_envar: QUAY_PASSWORD
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          name: push-to-app-catalog
          app_catalog: giantswarm-playground-catalog
          app_catalog_test: giantswarm-playground-test-catalog
          chart: gatling-app
          executor: app-build-suite
          requires:
            - push-to-quay
          filters:
            tags:
              only: /^v.*/
