version: 2.1

orbs:
  architect: giantswarm/architect@4.33.1

workflows:
  build:
    jobs:
      - architect/push-to-docker:
          name: push-to-quay
          context: architect
          image: quay.io/giantswarm/gatling-app
          username_envar: QUAY_USERNAME
          password_envar: QUAY_PASSWORD
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-to-giantswarm-playground-catalog
          context: architect
          executor: app-build-suite
          chart: gatling
          app_catalog: giantswarm-playground-catalog
          app_catalog_test: giantswarm-playground-test-catalog
          requires:
            - push-to-quay
          filters:
            tags:
              only: /^v.*/
