{{- if and (semverCompare "<1.25.0-0" .Capabilities.KubeVersion.Version) (not .Values.global.podSecurityStandards.enforced) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gatling.fullname" . }}
  labels:
    {{- include "gatling.labels" . | nindent 4 }}
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ include "gatling.fullname" . }}
  verbs:
  - use
{{- end }}
