apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}
  labels:
    job: {{ .Values.name }}
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  completions: {{ .Values.job.completions }}
  parallelism: {{ .Values.job.parallelism }}
  template:
    metadata:
      job: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}
      securityContext:
        runAsUser: {{ .Values.pod.userID }}
        runAsGroup: {{ .Values.pod.groupID }}
      {{- if .Values.simulation.url }}
      initContainers:
      - name: download
        image: {{ .Values.image.registry }}/{{ .Values.image.repo }}:{{ .Values.image.tag }}
        command:
        - wget
        args:
        - {{ .Values.simulation.url }}
        - -P user-files/simulations/
        volumeMounts:
        - name: simulationdir
          mountPath: "/opt/gatling/user-files/simulations"
      {{- end }}
      containers:
      - name: gatling
        image: {{ .Values.image.registry }}/{{ .Values.image.repo }}:{{ .Values.image.tag }}
        command:
        - gatling.sh
        args:
        - -s {{ .Values.simulation.name }}
        - -rf ./results/
        volumeMounts:
        - name: simulationdir
          mountPath: "/opt/gatling/user-files/simulations"
      restartPolicy: {{ .Values.pod.restartPolicy }}
      volumes:
      - name: simulationdir
      {{- if .Values.simulation.url }}
        emptyDir: {}
      {{- else }}
        configMap:
          name: {{ .Values.simulation.configMap.name }}
          optional: true
      {{- end }}
