kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}-network-policy
  labels:
    app: {{ .Values.name }}
    application.giantswarm.io/team: {{ index .Chart.Annotations "application.giantswarm.io/team" }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.name }}
      application.giantswarm.io/team: {{ index .Chart.Annotations "application.giantswarm.io/team" }}
  ingress: []
  egress:
  - {}
  policyTypes:
  - Egress
  - Ingress
