apiVersion: v1
appVersion: "3.2.1"
description: "Async Scala-Akka-Netty based Load Test Tool "
engine: gotpl
home: https://github.com/giantswarm/gatling-app
icon: https://s.giantswarm.io/app-icons/1/png/gatling-app-light.png
name: gatling-app
sources:
- https://raw.githubusercontent.com/giantswarm/gatling-app/v[[ .Version ]]/README.md
- https://github.com/gatling/gatling
version: [[ .Version ]]
annotations:
  application.giantswarm.io/team: team-cabbage
